---

- hosts: r1
  gather_facts: no
  tasks:

    - name: Add post-login banner
      vyos.vyos.vyos_banner:
        banner: post-login
        text: |
          Hello,
          VyOS World!
        state: present
