---

- hosts: r1

  connection: network_cli
  gather_facts: 'no'

  tasks:
    - name: Configure remote r1
      vyos_config:
        lines:
          - set system name-server 1.1.1.1
          - set service ssh disable-host-validation
          - set system login user vyos authentication public-keys docker@work type ssh-rsa
          - set system login user vyos authentication public-keys docker@work key "{{ lookup('file', 'id_rsa_docker.pub') }}"
          - set system time-zone Europe/Kiev
          - set interfaces ethernet eth0 description WAN
        #backup: yes
