name: Repo-sync-reuse

on:
    #pull_request:
    #  types:
    #    - closed
    #  branches:
    #    - current
    workflow_dispatch:

jobs:
  trigger-sync:
    uses: vyos/.github/.github/workflows/trigger-repo-sync.yml@feature/T6349-reusable-workflows
    secrets: inherit
