name: Repo-sync-reuse

on:
  #pull_request:
  #  types:
  #    - closed
  #  branches:
  #    - current
  workflow_dispatch:

#
jobs:
  trigger-sync:
    uses: sever-sever/vyos-automate/actions/workflows/repo-sync.yml
    secrets:
      REMOTE_REPO: ${{ secrets.REMOTE_REPO }}
      REMOTE_OWNER: ${{ secrets.REMOTE_OWNER }}
      PAT: ${{ secrets.PAT }}
